variables:
  COMMON_VERSION: 0.1.5
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

before_script:
  - pip install -q -U setuptools wheel
  - python3 --version
  - pylint --version
  - aws --version

stages:
  - test
  - build

lint:
  retry: 2
  tags:
    - python
  stage: test
  script:
    - pip install -q -U pylint
    - make lint
  only:
    refs:
      - merge_request

build-package:
  retry: 2
  tags:
    - python
  stage: build
  script:
    - make package
  only:
    refs:
      - merge_request

build-upload:
  retry: 2
  tags:
    - python
  stage: build
  script:
    - make package-upload
  only:
    refs:
      - master
