variables:
  COMMON_VERSION: 0.9.0
  GIT_COMMIT_EMAIL: support@trivialsec.com
  GIT_COMMIT_NAME: gitlab-ci

before_script:
  - make --version
  - python3 --version
  - pylint --version
  - echo semgrep $(semgrep --version)

stages:
  - build
  - tests
  - release

test:sast:
  tags:
    - linode
  stage: tests
  script:
    - make semgrep-sast-ci
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: sast-results
    paths:
      - semgrep-ci.json

test:xss:
  tags:
    - linode
  stage: tests
  script:
    - make semgrep-xss-ci
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: xss-results
    paths:
      - semgrep-flask-xss.json

test:lint:
  tags:
    - linode
  stage: tests
  script:
    - make install
    - make pylint-ci
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: lint-results
    paths:
      - pylint.json

build:wheel:
  tags:
    - linode
  stage: build
  script:
    - make archive
  only:
    refs:
      - merge_request

release:wheel:
  tags:
    - linode
  stage: release
  script:
    - make archive
  only:
    refs:
      - main
  artifacts:
    name: trivialsec_common-${COMMON_VERSION}-py2.py3-none-any.whl
    paths:
      - trivialsec.tar.gz

release:tag:
  tags:
    - linode
  stage: release
  script:
    - mkdir -p ~/.ssh
    - aws s3 cp --only-show-errors s3://stateful-trivialsec/deploy-keys/gitlab_ci ~/.ssh/gitlab_ci
    - chmod 400 ~/.ssh/gitlab_ci
    - eval $(ssh-agent)>/dev/null
    - ssh-add ~/.ssh/gitlab_ci >/dev/null 2>&1
    - git remote set-url --push origin git@gitlab.com:$CI_PROJECT_PATH.git
    - git remote show origin
    - git config user.name $GIT_COMMIT_NAME
    - git config user.email $GIT_COMMIT_EMAIL
    - git tag -f ${COMMON_VERSION}
    - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
    - git push -f origin ${COMMON_VERSION}
  only:
    refs:
      - main
