variables:
  COMMON_VERSION: 0.5.0

before_script:
  - make --version
  - python3 --version
  - pylint --version
  - echo semgrep $(semgrep --version)

stages:
  - build
  - test

test:lint:
  tags:
    - linode
  stage: test
  script:
    - make lint
  only:
    refs:
      - merge_request

test:sast:
  tags:
    - linode
  stage: test
  script:
    - make sast
  only:
    refs:
      - merge_request

test:xss:
  tags:
    - linode
  stage: test
  script:
    - make xss
  only:
    refs:
      - merge_request

build:wheel:
  tags:
    - linode
  stage: build
  script:
    - make install
  only:
    refs:
      - merge_request
