variables:
  COMMON_VERSION: 0.5.1

before_script:
  - make --version
  - python3 --version
  - pylint --version
  - echo semgrep $(semgrep --version)
  - make install

stages:
  - build
  - tests
  - release

test:sast:
  tags:
    - linode
  stage: tests
  script:
    - make semgrep-sast-ci
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: sast-results
    paths:
      - semgrep-ci.json

test:xss:
  tags:
    - linode
  stage: tests
  script:
    - make semgrep-xss-ci
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: xss-results
    paths:
      - semgrep-flask-xss.json

test:lint:
  tags:
    - linode
  stage: tests
  script:
    - make pylint-ci
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: lint-results
    paths:
      - pylint.json

build:wheel:
  tags:
    - linode
  stage: build
  script:
    - make archive
  only:
    refs:
      - merge_request

release:wheel:
  tags:
    - linode
  stage: release
  script:
    - make archive
  only:
    refs:
      - main
  artifacts:
    name: trivialsec_common-${COMMON_VERSION}-py2.py3-none-any.whl
    paths:
      - trivialsec.tgz

release:tag:
  tags:
    - linode
  stage: release
  script:
    - git tag -f $COMMON_VERSION
    - git push origin --delete $COMMON_VERSION
    - git push origin $COMMON_VERSION
  only:
    refs:
      - main
  release:
      name: 'v$COMMON_VERSION'
      tag_name: '$CI_COMMIT_TAG'
      description: '$CI_COMMIT_MESSAGE'
